In [7]:
import requests
import os
from dotenv import load_dotenv
import time
load_dotenv()

shop_url = "https://ur1k4u-d2.myshopify.com"
api_version = "2025-01"

def get_all_products(shop_url, api_version):
    all_products = []
    url = f"{shop_url}/admin/api/{api_version}/products.json"
    headers = {"X-Shopify-Access-Token": os.getenv("SHOPIFY_API_KEY")}
    params = {"limit": 250}
    response = requests.get(url, headers=headers, params=params)
    all_products.extend(response.json()["products"])
    try:
        while response.links["next"]:
            response = requests.get(response.links["next"]["url"], headers=headers)
            all_products.extend(response.json()["products"])
            time.sleep(2)
    except KeyError:
        return all_products
    
all_products = get_all_products(shop_url, api_version)

In [90]:
all_products[0].keys()

dict_keys(['id', 'title', 'body_html', 'vendor', 'product_type', 'created_at', 'handle', 'updated_at', 'published_at', 'template_suffix', 'published_scope', 'tags', 'status', 'admin_graphql_api_id', 'variants', 'options', 'images', 'image'])

In [2]:
import requests
import os
from dotenv import load_dotenv
import time
load_dotenv()

shop_url = "https://jacksonshardware.myshopify.com"
api_version = "2025-01"

def get_all_products(shop_url, api_version):
    all_products = []
    url = f"{shop_url}/admin/api/{api_version}/products.json"
    headers = {"X-Shopify-Access-Token": os.getenv("SHOPIFY_API_KEY")}
    params = {"limit": 250}
    response = requests.get(url, headers=headers, params=params)
    all_products.extend(response.json()["products"])
    try:
        while response.links["next"]:
            response = requests.get(response.links["next"]["url"], headers=headers)
            all_products.extend(response.json()["products"])
            time.sleep(2)
            print(len(all_products))
    except KeyError:
        return all_products
    
all_products = get_all_products(shop_url, api_version)

In [3]:
all_products[0].keys()

dict_keys(['id', 'title', 'body_html', 'vendor', 'product_type', 'created_at', 'handle', 'updated_at', 'published_at', 'template_suffix', 'published_scope', 'tags', 'status', 'admin_graphql_api_id', 'variants', 'options', 'images', 'image'])

In [7]:
len(all_products)

7345

In [8]:
import pandas as pd
df = pd.DataFrame(all_products)

In [16]:
df = df[~df['status'].isin(['archived', 'draft'])]

In [17]:
df.status.value_counts()

status
active    7015
Name: count, dtype: int64

In [10]:
df.body_html

0       <strong>Carolina® Women's ELM Work Boots, CA42...
1       <strong>Carolina® Men's Bruno Lo Work Boots, C...
2       <strong>Carolina® Men's Flagstone Hiker, CA552...
3       <strong>Carolina® Men's Cathode Work Boots, CA...
4       <strong>Carolina® Men's Cathode Work Boots, CA...
                              ...
7340    <strong>ZIRCON® MultiScanner® Stud Finder, 1-1...
7341    <strong>ZIRCON® StudSensor™ Stud Finder, 1-1/2...
7342    <strong>ZIRCON® StudSensor™ Stud Finder, 1-1/2...
7343    <strong>ZIRCON® StudSensor™ Stud Finder, 3/4 i...
7344    <strong>ZIRCON® StudSensor™ Stud Finder, 3/4 i...
Name: body_html, Length: 7345, dtype: object

In [11]:
df.isna()

,id,title,body_html,vendor,product_type,created_at,handle,updated_at,published_at,template_suffix,published_scope,tags,status,admin_graphql_api_id,variants,options,images,image
0,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7340,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
7341,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
7342,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
7343,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
7344,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False

In [12]:
df.fillna("")

,id,title,body_html,vendor,product_type,created_at,handle,updated_at,published_at,template_suffix,published_scope,tags,status,admin_graphql_api_id,variants,options,images,image
0,7883874435224,Carolina® CA421 Series CA421-9M Women's ELM Wo...,"<strong>Carolina® Women's ELM Work Boots, CA42...",Carolina®,Home Goods,2024-01-25T08:56:17-08:00,womens-8-logger,2025-01-12T23:43:24-08:00,2024-02-28T22:12:40-08:00,,web,,active,gid://shopify/Product/7883874435224,"[{'product_id': 7883874435224, 'id': 432490676...","[{'product_id': 7883874435224, 'id': 100127871...","[{'id': 44185853493400, 'alt': None, 'position...","{'id': 44185853493400, 'alt': None, 'position'..."
1,7883874828440,Carolina® CA5020 Series CA5020-9-D Men's Bruno...,"<strong>Carolina® Men's Bruno Lo Work Boots, C...",Carolina®,Home Goods,2024-01-25T08:56:24-08:00,mens-6-wtrprf-broad-toe,2024-12-19T10:03:59-08:00,2024-02-28T22:12:42-08:00,,web,,active,gid://shopify/Product/7883874828440,"[{'id': 43249068998808, 'product_id': 78838748...","[{'id': 10012787507352, 'product_id': 78838748...","[{'id': 44185854673048, 'alt': None, 'position...","{'id': 44185854673048, 'alt': None, 'position'..."
2,7883754176664,Carolina® CA5525 Series CA5525-13-D Men's Flag...,"<strong>Carolina® Men's Flagstone Hiker, CA552...",Carolina®,Home Goods,2024-01-25T08:18:52-08:00,mens-6-wtrprf-comp-toe,2024-12-27T11:27:51-08:00,2024-02-28T22:12:43-08:00,,web,,active,gid://shopify/Product/7883754176664,"[{'id': 43248793976984, 'product_id': 78837541...","[{'id': 10012661678232, 'product_id': 78837541...","[{'id': 44185853296792, 'alt': None, 'position...","{'id': 44185853296792, 'alt': None, 'position'..."
3,7883875287192,Carolina® CA5589 Series CA5589-10-D Men's Cath...,"<strong>Carolina® Men's Cathode Work Boots, CA...",Carolina®,Home Goods,2024-01-25T08:56:31-08:00,cathode-8-waterproof-dwo-2,2024-12-13T21:15:08-08:00,2024-02-28T00:34:18-08:00,,web,,active,gid://shopify/Product/7883875287192,"[{'id': 43249070375064, 'product_id': 78838752...","[{'id': 10012787966104, 'product_id': 78838752...","[{'id': 44179030737048, 'alt': None, 'position...","{'id': 44179030737048, 'alt': None, 'position'..."
4,7883875385496,Carolina® CA5589 Series CA5589-10-EE Men's Cat...,"<strong>Carolina® Men's Cathode Work Boots, CA...",Carolina®,Home Goods,2024-01-25T08:56:32-08:00,cathode-8-waterproof-dwo-3,2024-12-22T13:46:44-08:00,2024-02-28T00:34:20-08:00,,web,,active,gid://shopify/Product/7883875385496,"[{'id': 43249070506136, 'product_id': 78838753...","[{'id': 10012788064408, 'product_id': 78838753...","[{'id': 44179031163032, 'alt': None, 'position...","{'id': 44179031163032, 'alt': None, 'position'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7340,7660141117592,"ZIRCON® MultiScanner® 61910 Stud Finder, 1-1/2...","<strong>ZIRCON® MultiScanner® Stud Finder, 1-1...",ZIRCON®,Tools,2023-07-13T12:24:14-07:00,multiscanner-1step-i520,2024-12-13T20:49:40-08:00,2024-02-27T22:10:00-08:00,,web,,active,gid://shopify/Product/7660141117592,"[{'id': 42731508367512, 'product_id': 76601411...","[{'id': 9739225989272, 'product_id': 766014111...","[{'id': 44177445224600, 'alt': None, 'position...","{'id': 44177445224600, 'alt': None, 'position'..."
7341,7660233425048,"ZIRCON® StudSensor™ 61903 Stud Finder, 1-1/2 i...","<strong>ZIRCON® StudSensor™ Stud Finder, 1-1/2...",ZIRCON®,Tools,2023-07-13T13:00:01-07:00,studsensor-pro-sl-ac,2024-12-13T20:54:39-08:00,2024-02-27T22:40:42-08:00,,web,,active,gid://shopify/Product/7660233425048,"[{'id': 42731611455640, 'product_id': 76602334...","[{'id': 9739319017624, 'product_id': 766023342...","[{'id': 44177808130200, 'alt': None, 'position...","{'id': 44177808130200, 'alt': None, 'position'..."
7342,7660126306456,"ZIRCON® StudSensor™ 61961 Stud Finder, 1-1/2 i...","<strong>ZIRCON® StudSensor™ Stud Finder, 1-1/2...",ZIRCON®,Tools,2023-07-13T12:18:13-07:00,studsensor-i65-onestep,2024-12-13T20:48:53-08:00,2024-02-27T22:05:15-08:00,,web,,active,gid://shopify/Product/7660126306456,"[{'id': 42731488379032, 'product_id': 76601263...","[{'id': 9739211047064, 'product_id': 766012630...","[{'id': 44177390010520, 'alt': None, 'position...","{'id': 44177390010520, 'alt': None, 'position'..."
7343,7660085543064,"ZIRCON® StudSensor™ 63569 Stud Finder, 3/4 in ...","<strong>ZIRCON® StudSensor™ Stud Finder, 3/4 i...",ZIRCON®,Tools,2023-07-13T12:02:52-07:00,zircon-studsensor-e30,2024-12-28T11:03:37-08:00,2024-02-27T21:48:34-08:00,,web,,active,gid://shopify/Product/7660085543064,"[{'id': 42731441586328, 'product_id': 76600855...","[{'id': 9739169824920, 'product_id': 766008554...","[{'id': 44177181212824, 'alt': None, 'position...","{'id': 44177181212824, 'alt': None, 'position'..."
7344,7660128108696,"ZIRCON® StudSensor™ 64919 Stud Finder, 3/4 in ...","<strong>ZIRCON® StudSensor™ Stud Finder, 3/4 i...",ZIRCON®,Tools,2023-07-13T12:18:41-07:00,zircon-studsensor-e50,2024-12-13T20:48:59-08:00,2024-02-27T22:05:51-08:00,,web,,active,gid://shopify/Product/7660128108696,"[{'id': 42731490541720, 'product_id': 76601281...","[{'id': 9739212849304, 'product_id': 766012810...","[{'id': 44177396465816, 'alt': None, 'position...","{'id': 44177396465816, 'alt': None, 'position'..."

In [82]:
from bs4 import BeautifulSoup

# Function to clean HTML tags from the 'body_html' column
def clean_html_tags(row):
    html_content = row["body_html"]  # Access the specific column
    soup = BeautifulSoup(html_content, "html.parser")
    text = soup.get_text()
    row["body_html"] = text  # Update the column in the row
    return row

def get_img_src(row):
    img_list = row["images"]
    if isinstance(img_list, list):
        # Extract all "src" attributes from the list of dictionaries
        img_src_list = [img["src"] for img in img_list if "src" in img]
        row["image_list"] = img_src_list  # Store as a list
    else:
        row["image_list"] = []  # Handle cases where no images are found
    return row

def create_expanded_descriptions(row):
    if row["body_html"] == "" and row["tags"] == "":
        row["expanded_description"] = row["title"]
    elif row["body_html"] == ""and row["tags"] != "":
        row["expanded_description"] = "Title: " + row["title"] + " Tags: " + row["tags"]
    elif row["body_html"] != "" and row["tags"] == "":
        row["expanded_description"] = "Title: " + row["title"] + row["body_html"]
    else:
        row["expanded_description"] = "Title: " + row["title"] + " Tags: " + row["tags"] + row["body_html"]
    return row


def df_preprocessing(df):
    df = df[df["status"]=="active"]
    df.fillna("",inplace=True)
    df = df.apply(clean_html_tags, axis=1)  # Apply clean_html_tags to each row
    df = df.apply(get_img_src, axis=1)     # Apply get_img_src to each row
    df = df.apply(create_expanded_descriptions, axis=1)  # Apply create_expanded_descriptions to each row
    df = df.rename(columns={"body_html": "description"})
    df = df[["id","title","description","expanded_description","image_list","tags","handle"]]
    return df

# Apply the functions to the DataFrame
df = df.apply(clean_html_tags, axis=1)  # Apply clean_html_tags to each row
df = df.apply(get_img_src, axis=1)     # Apply get_img_src to each row
df = df.apply(create_expanded_descriptions, axis=1)  # Apply create_expanded_descriptions to each row

# Print the updated DataFrame
print(df.head())

C:\Users\lsiva\AppData\Local\Temp\ipykernel_18372\3815832880.py:6: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = BeautifulSoup(html_content, "html.parser")

              id  \
0  7883874435224
1  7883874828440
2  7883754176664
3  7883875287192
4  7883875385496

                                                                                                                   title  \
0                 Carolina® CA421 Series CA421-9M Women's ELM Work Boots, SZ 9, M W, Dark Brown, Soft Toe, Leather Upper
1    Carolina® CA5020 Series CA5020-9-D Men's Bruno Lo Work Boots, SZ 9, D W, Brown, Soft Toe, Leather Upper, Waterproof
2  Carolina® CA5525 Series CA5525-13-D Men's Flagstone Hiker, SZ 13, D W, Brown/Gray, Carbon Composite Toe, Lace Closure
3          Carolina® CA5589 Series CA5589-10-D Men's Cathode Work Boots, SZ 10, D W, Brown, Composite Toe, Leather Upper
4        Carolina® CA5589 Series CA5589-10-EE Men's Cathode Work Boots, SZ 10, EE W, Brown, Composite Toe, Leather Upper

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 body_html  \
0  Carolina® Women's ELM Work Boots, CA421 Series, SZ 9, Dark Brown, Soft Toe, Leather Upper, Rubber Outsole, Pillow Cushion™ Insole, Taibrelle Lining, Resists: Oil and Slip, M Width, 8 in Height This rugged women's 8 in logger is built for Work™. It's crafted with a shovel worthy, steel shank for added support and an aggressive rubber outsole for dependable traction. Features:  Electrical hazard - footwear tested by an independent lab that can withstand applications of 18000 V at 60 Hz for one minute without leakage Steel shank - A thin piece of metal built between the insole and outsole of the boot that helps provide stability, structure and support Pillow Cushion™ 1 footbed - A layer of memory foam that wraps the foot in comfort Combined with existing insole systems, it offers the ultimate in cushioned comfort Soft toe - boots that are made without safety toe components Dark brown soggy leather upper Welt construction Oil and slip-resisting one-piece rubber lug outsole  Other Attri...
1  Carolina® Men's Bruno Lo Work Boots, CA5020 Series, SZ 9, Brown, Soft Toe, Leather Upper, EVA Midsole, Rubber Outsole, Pillow Cushion™ Insole, Waterproof, Resists: Slip, D Width, 6 in Height A tough boot with extra room for comfort in the toe - our men's 6 in waterproof broad toe work boot. Your hardworking feet will get enduring support with our Pillow Cushion™ insole and removable ag7™ footbed and a waterproof scubaliner™ adds to the comfort. The oil and slip-resisting outsole provides durability and traction. Features:  Electrical hazard - footwear tested by an independent lab that can withstand applications of 18000 V at 60 Hz for one minute without leakage Non-metallic shank - a composite alternative to a steel shank, with the stability, structure and support you need Ideal for worksites with metal detectors at access points so you can work without repeatedly setting off the metal detector Slip-resisting - soles designed and constructed with materials to meet the standard for ...
2  Carolina® Men's Flagstone Hiker, CA5525 Series, SZ 13, Brown/Gray, Carbon Composite Toe, Leather Upper, EVA Midsole, Rubber Outsole, Mesh Lining, Lace Closure, Waterproof, Resists: Abrasion, Oil and Slip, D Width, 6 in Height This men's 6 in waterproof carbon composite toe 4x4 hiker is built for performance and durability. Set on a heavy-duty oil and slip-resisting rubber outsole, it's packed with the features you need on the job - from the lightweight carbon composite safety toe cap to the waterproof scubaliner™ and abrasion-resisting 4x4 TigerTip® toe. Features:  Electrical hazard - footwear tested by an independent lab that can withstand applications of 18000 V at 60 Hz for one minute without leakage Non-metallic shank - a composite alternative to a steel shank, with the stability, structure and support you need Ideal for worksites with metal detectors at access points so you can work without repeatedly setting off the metal detector Slip-resisting - soles designed and construct...
3  Carolina® Men's Cathode Work Boots, CA5589 Series, SZ 10, Brown, Composite Toe, Leather Upper, Polyurethane Midsole, Rubber Outsole, Mesh Lining, Waterproof, Resists: Oil and Slip, D Width, 8 in Height This men's 8 in waterproof composite toe work boot makes an excellent work boot or warehouse shoe. Its waterproof scubaliner™ lining, composite safety toe cap and oil and slip-resisting outsole come together to deliver comfort and safety. Features:  Electrical hazard - footwear tested by an independent lab that can withstand applications of 18000 V at 60 Hz for one minute without leakage Non-metallic shank - a composite alternative to a steel shank, with the stability, structure and support you need Ideal for worksites with metal detectors at access points so you can work without repeatedly setting off the metal detector Slip-resisting - soles designed and constructed with materials to meet the standard for slip-resistance Waterproof scubaliner™ - CAROLINA®'s exclusive proprietary wa...
4  Carolina® Men's Cathode Work Boots, CA5589 Series, SZ 10, Brown, Composite Toe, Leather Upper, Polyurethane Midsole, Rubber Outsole, Mesh Lining, Waterproof, Resists: Oil and Slip, EE Width, 8 in Height This men's 8 in waterproof composite toe work boot makes an excellent work boot or warehouse shoe. Its waterproof scubaliner™ lining, composite safety toe cap and oil and slip-resisting outsole come together to deliver comfort and safety. Features:  Electrical hazard - footwear tested by an independent lab that can withstand applications of 18000 V at 60 Hz for one minute without leakage Non-metallic shank - a composite alternative to a steel shank, with the stability, structure and support you need Ideal for worksites with metal detectors at access points so you can work without repeatedly setting off the metal detector Slip-resisting - soles designed and constructed with materials to meet the standard for slip-resistance Waterproof scubaliner™ - CAROLINA®'s exclusive proprietary w...

      vendor product_type                 created_at  \
0  Carolina®   Home Goods  2024-01-25T08:56:17-08:00
1  Carolina®   Home Goods  2024-01-25T08:56:24-08:00
2  Carolina®   Home Goods  2024-01-25T08:18:52-08:00
3  Carolina®   Home Goods  2024-01-25T08:56:31-08:00
4  Carolina®   Home Goods  2024-01-25T08:56:32-08:00

                       handle                 updated_at  \
0             womens-8-logger  2025-01-12T23:43:24-08:00
1     mens-6-wtrprf-broad-toe  2024-12-19T10:03:59-08:00
2      mens-6-wtrprf-comp-toe  2024-12-27T11:27:51-08:00
3  cathode-8-waterproof-dwo-2  2024-12-13T21:15:08-08:00
4  cathode-8-waterproof-dwo-3  2024-12-22T13:46:44-08:00

                published_at template_suffix published_scope tags  status  \
0  2024-02-28T22:12:40-08:00            None             web       active
1  2024-02-28T22:12:42-08:00            None             web       active
2  2024-02-28T22:12:43-08:00            None             web       active
3  2024-02-28T00:34:18-08:00            None             web       active
4  2024-02-28T00:34:20-08:00            None             web       active

                  admin_graphql_api_id  \
0  gid://shopify/Product/7883874435224
1  gid://shopify/Product/7883874828440
2  gid://shopify/Product/7883754176664
3  gid://shopify/Product/7883875287192
4  gid://shopify/Product/7883875385496

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  variants  \
0  [{'product_id': 7883874435224, 'id': 43249067688088, 'title': '10 MEDIUM', 'price': '139.99', 'position': 1, 'inventory_policy': 'deny', 'compare_at_price': None, 'option1': '10 MEDIUM', 'option2': None, 'option3': None, 'created_at': '2024-01-25T08:56:17-08:00', 'updated_at': '2024-02-29T21:12:12-08:00', 'taxable': True, 'barcode': '726363506811', 'fulfillment_service': 'manual', 'grams': 454, 'inventory_management': 'shopify', 'requires_shipping': True, 'sku': 'CA42110M', 'weight': 1.0, 'weight_unit': 'lb', 'inventory_item_id': 45345742946456, 'inventory_quantity': 0, 'old_inventory_quantity': 0, 'admin_graphql_api_id': 'gid://shopify/ProductVariant/43249067688088', 'image_id': None}, {'product_id': 7883874435224, 'id': 43249067753624, 'title': '11 MEDIUM', 'price': '139.99', 'position': 2, 'inventory_policy': 'deny', 'compare_at_price': None, 'option1': '11 MEDIUM', 'option2': None, 'option3': None, 'created_at': '2024-01-25T08:56:17-08:00', 'updated_at': '2024-02-29T21:12:12-08...
1  [{'id': 43249068998808, 'product_id': 7883874828440, 'title': '10 EXTRA EXTRA WIDE', 'price': '169.99', 'position': 1, 'inventory_policy': 'deny', 'compare_at_price': None, 'option1': '10 EXTRA EXTRA WIDE', 'option2': None, 'option3': None, 'created_at': '2024-01-25T08:56:24-08:00', 'updated_at': '2024-02-29T21:12:13-08:00', 'taxable': True, 'barcode': '726363508747', 'fulfillment_service': 'manual', 'grams': 454, 'inventory_management': 'shopify', 'requires_shipping': True, 'sku': 'CA5020102E', 'weight': 1.0, 'weight_unit': 'lb', 'inventory_item_id': 45345744257176, 'inventory_quantity': 1, 'old_inventory_quantity': 1, 'admin_graphql_api_id': 'gid://shopify/ProductVariant/43249068998808', 'image_id': None}, {'id': 43249069097112, 'product_id': 7883874828440, 'title': '10 REGULAR', 'price': '169.99', 'position': 2, 'inventory_policy': 'deny', 'compare_at_price': None, 'option1': '10 REGULAR', 'option2': None, 'option3': None, 'created_at': '2024-01-25T08:56:24-08:00', 'updated_at':...
2  [{'id': 43248793976984, 'product_id': 7883754176664, 'title': '10 EXTRA WIDE', 'price': '164.99', 'position': 1, 'inventory_policy': 'deny', 'compare_at_price': None, 'option1': '10 EXTRA WIDE', 'option2': None, 'option3': None, 'created_at': '2024-01-25T08:18:52-08:00', 'updated_at': '2024-02-29T21:11:14-08:00', 'taxable': True, 'barcode': '726363658992', 'fulfillment_service': 'manual', 'grams': 454, 'inventory_management': 'shopify', 'requires_shipping': True, 'sku': 'CA552510EE', 'weight': 1.0, 'weight_unit': 'lb', 'inventory_item_id': 45345469890712, 'inventory_quantity': 1, 'old_inventory_quantity': 1, 'admin_graphql_api_id': 'gid://shopify/ProductVariant/43248793976984', 'image_id': None}, {'id': 43248794075288, 'product_id': 7883754176664, 'title': '10 REGULAR', 'price': '164.99', 'position': 2, 'inventory_policy': 'deny', 'compare_at_price': None, 'option1': '10 REGULAR', 'option2': None, 'option3': None, 'created_at': '2024-01-25T08:18:53-08:00', 'updated_at': '2024-02-29...
3                                                                                                                                                                                                                                                                                                          [{'id': 43249070375064, 'product_id': 7883875287192, 'title': 'Default Title', 'price': '84.99', 'position': 1, 'inventory_policy': 'deny', 'compare_at_price': None, 'option1': 'Default Title', 'option2': None, 'option3': None, 'created_at': '2024-01-25T08:56:31-08:00', 'updated_at': '2024-02-29T21:12:14-08:00', 'taxable': True, 'barcode': '726363661367', 'fulfillment_service': 'manual', 'grams': 454, 'inventory_management': 'shopify', 'requires_shipping': True, 'sku': 'CA558910D', 'weight': 1.0, 'weight_unit': 'lb', 'inventory_item_id': 45345745633432, 'inventory_quantity': 0, 'old_inventory_quantity': 0, 'admin_graphql_api_id': 'gid://shopify/ProductVariant/43249070375064', 'image_id': None}]
4                                                                                                                                                                                                                                                                                                         [{'id': 43249070506136, 'product_id': 7883875385496, 'title': 'Default Title', 'price': '84.99', 'position': 1, 'inventory_policy': 'deny', 'compare_at_price': None, 'option1': 'Default Title', 'option2': None, 'option3': None, 'created_at': '2024-01-25T08:56:32-08:00', 'updated_at': '2024-02-29T21:12:14-08:00', 'taxable': True, 'barcode': '726363661251', 'fulfillment_service': 'manual', 'grams': 454, 'inventory_management': 'shopify', 'requires_shipping': True, 'sku': 'CA558910EE', 'weight': 1.0, 'weight_unit': 'lb', 'inventory_item_id': 45345745764504, 'inventory_quantity': 0, 'old_inventory_quantity': 0, 'admin_graphql_api_id': 'gid://shopify/ProductVariant/43249070506136', 'image_id': None}]

                                                                                                                                                                                                                                                                                                                                                                                                                            options  \
0                                                                          [{'product_id': 7883874435224, 'id': 10012787114136, 'name': 'size', 'position': 1, 'values': ['10 MEDIUM', '11 MEDIUM', '5 MEDIUM', '5-1/2 MEDIUM', '6 MEDIUM', '6 Wide', '6-1/2 MEDIUM', '6-1/2 Wide', '7 MEDIUM', '7 Wide', '7-1/2 MEDIUM', '7-1/2 Wide', '8 MEDIUM', '8 Wide', '8-1/2 MEDIUM', '8-1/2 Wide', '9 MEDIUM', '9 Wide', '9-1/2 MEDIUM']}]
1  [{'id': 10012787507352, 'product_id': 7883874828440, 'name': 'size', 'position': 1, 'values': ['10 EXTRA EXTRA WIDE', '10 REGULAR', '10-1/2 EXTRA EXTRA WIDE', '10-1/2 REGULAR', '11 REGULAR', '11-1/2 REGULAR', '12 REGULAR', '13 REGULAR', '14 REGULAR', '7 REGULAR', '7-1/2 REGULAR', '8 REGULAR', '8-1/2 EXTRA EXTRA WIDE', '8-1/2 REGULAR', '9 EXTRA EXTRA WIDE', '9 REGULAR', '9-1/2 EXTRA EXTRA WIDE', '9-1/2 REGULAR']}]
2                                                            [{'id': 10012661678232, 'product_id': 7883754176664, 'name': 'size', 'position': 1, 'values': ['10 EXTRA WIDE', '10 REGULAR', '10-1/2 EXTRA WIDE', '10-1/2 REGULAR', '11 REGULAR', '11-1/2 REGULAR', '12 REGULAR', '13 REGULAR', '8 EXTRA WIDE', '8 REGULAR', '8-1/2 EXTRA WIDE', '8-1/2 REGULAR', '9 EXTRA WIDE', '9 REGULAR', '9-1/2 EXTRA WIDE', '9-1/2 REGULAR']}]
3                                                                                                                                                                                                                                                                                                                [{'id': 10012787966104, 'product_id': 7883875287192, 'name': 'Title', 'position': 1, 'values': ['Default Title']}]
4                                                                                                                                                                                                                                                                                                                [{'id': 10012788064408, 'product_id': 7883875385496, 'name': 'Title', 'position': 1, 'values': ['Default Title']}]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    images  \
0  [{'id': 44185853493400, 'alt': None, 'position': 1, 'product_id': 7883874435224, 'created_at': '2024-02-29T04:12:51-08:00', 'updated_at': '2024-02-29T04:12:51-08:00', 'admin_graphql_api_id': 'gid://shopify/ProductImage/44185853493400', 'width': 2100, 'height': 2100, 'src': 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/CAROLINA_CA421_10M.jpg?v=1709208770', 'variant_ids': []}, {'id': 44185853526168, 'alt': None, 'position': 2, 'product_id': 7883874435224, 'created_at': '2024-02-29T04:12:51-08:00', 'updated_at': '2024-02-29T04:12:51-08:00', 'admin_graphql_api_id': 'gid://shopify/ProductImage/44185853526168', 'width': 2100, 'height': 2100, 'src': 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/CAROLINA_CA421_10M_3_a62afc99-518d-4aba-a60f-25b408095b14.jpg?v=1709208770', 'variant_ids': []}, {'id': 44185853558936, 'alt': None, 'position': 3, 'product_id': 7883874435224, 'created_at': '2024-02-29T04:12:51-08:00', 'updated_at': '2024-02-29T04:12:51-08:00', 'admin_gra...
1  [{'id': 44185854673048, 'alt': None, 'position': 1, 'product_id': 7883874828440, 'created_at': '2024-02-29T04:12:55-08:00', 'updated_at': '2024-02-29T04:12:55-08:00', 'admin_graphql_api_id': 'gid://shopify/MediaImage/37239623942296', 'width': 2000, 'height': 2000, 'src': 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/CAROLINA_CA5020_10_2E_12babaea-da93-498f-8673-d726606bef10.jpg?v=1709208775', 'variant_ids': []}, {'id': 44185854705816, 'alt': None, 'position': 2, 'product_id': 7883874828440, 'created_at': '2024-02-29T04:12:55-08:00', 'updated_at': '2024-02-29T04:12:55-08:00', 'admin_graphql_api_id': 'gid://shopify/MediaImage/37239623975064', 'width': 2000, 'height': 2000, 'src': 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/CAROLINA_CA5020_10_2E_2_f066de39-ea53-44c5-be7b-fb443759460e.jpg?v=1709208775', 'variant_ids': []}, {'id': 44185854738584, 'alt': None, 'position': 3, 'product_id': 7883874828440, 'created_at': '2024-02-29T04:12:55-08:00', 'updated_at': ...

In [ ]:
df.expanded_description

In [83]:
product_dataframe = df

In [ ]:
pd.set_option('display.max_colwidth', 1000)
pd.set_option('display.max_rows', 100000)
product_dataframe.images

In [ ]:
def rows_without_images(df, column_name):
    return df[df[column_name].apply(lambda x: not BeautifulSoup(x, "html.parser").find("img") if isinstance(x, str) else True)]

result = rows_without_images(df, 'images')
result.head()

In [84]:
cleaned_df = df_preprocessing(df)

C:\Users\lsiva\AppData\Local\Temp\ipykernel_18372\3815832880.py:6: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = BeautifulSoup(html_content, "html.parser")

In [88]:
cleaned_df.to_csv("products.csv",index=False)

In [89]:
cleaned_products_json = cleaned_df.to_json(orient='records')
with open("products.json","w") as f:
    f.write(cleaned_products_json)

In [ ]:
from langchain.document_loaders.json_loader import JSONLoader
# Define the metadata extraction function.
def metadata_func(record: dict, metadata: dict) -> dict:
    metadata["id"] = record.get("id")
    metadata["title"] = record.get("title")
    metadata["tags"] = record.get("tags")
    metadata["images_list"] = record.get("images_list")
    metadata["handle"] = record.get("handle")
    return metadata


loader = JSONLoader(
    file_path='./products.json',
    jq_schema='.[]',
    content_key="expanded_description",
    metadata_func=metadata_func
)

documents = loader.load()

In [ ]:
from langchain.text_splitter import SentenceTransformersTokenTextSplitter
splitter = SentenceTransformersTokenTextSplitter(chunk_overlap=0)

def count_tokens(text):
    return splitter.count_tokens(text=text)

summed_tokens = 0
for product in documents:
    summed_tokens += count_tokens(product.page_content)

summed_tokens / 1000 * 0.0001

In [51]:
from utils import load_vectorstore
from dotenv import load_dotenv

load_dotenv()

vectorstore = load_vectorstore(vectorstore_path="./shopify_langchain_testing_vectorstore",index_name="products")

ValueError: The de-serialization relies loading a pickle file. Pickle files can be modified to deliver a malicious payload that results in execution of arbitrary code on your machine.You will need to set `allow_dangerous_deserialization` to `True` to enable deserialization. If you do this, make sure that you trust the source of the data. For example, if you are loading a file that you created, and know that no one else has modified the file, then this is safe to do. Do not set this to `True` if you are loading a file from an untrusted source (e.g., some random site on the internet.).

In [48]:
from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

text = "This is a test document."
query_result = embeddings.embed_query(text)

# show only the first 100 characters of the stringified vector
print(str(query_result)[:100] + "...")

d:\lang_shop\langchain_shopify\Lib\site-packages\huggingface_hub\file_download.py:140: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\lsiva\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

[-0.03833858668804169, 0.1234646588563919, -0.02864295244216919, 0.05365271866321564, 0.008845429867...

In [99]:
from util import load_vectorstore
vectorstore = load_vectorstore(vectorstore_path="./shopify_langchain_testing_vectorstore",index_name="products")
results = vectorstore.similarity_search("i want Work Boots",k=10)

In [100]:
print(results)
for i in results:
    print(i.metadata["image_list"])

[Document(id='a20c6e5b-cf40-4402-8b62-7051f9b7df71', metadata={'source': 'D:\\lang_shop\\products.json', 'seq_num': 6659, 'id': 7883890196632, 'title': "Wolverine® W08288 Series W08288-11EW Men's Work Boots, SZ 11, EW W, Tan, Moc, Soft Toe, Leather Upper, Waterproof", 'tags': '', 'image_list': ['https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_7c38f3e3-966f-4d88-8b1b-eb5d02cc9658.jpg?v=1709133517', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_2_899509a8-1cd8-48bc-b7b9-c7f82650901b.jpg?v=1709133517', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_4_6b20edf6-9042-43c4-8d98-7048ac581963.jpg?v=1709133517', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_1_f0b00c7c-1208-4a9c-b074-b354aeebac7b.jpg?v=1709133517', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_3_f4a10372-235f-4112-93f6-be2d43c4836b.jpg?v=1709133517'], 'handle': 'work-wedge-brn-moc-toe-11-ew'}, page_content="Title: Wolverine® W08288 Series W08288-11EW Men's Work Boots, SZ 11, EW W, Tan, Moc, Soft Toe, Leather Upper, WaterproofWolverine® Men's Work Boots, W08288 Series, SZ 11, Tan, Moc, Soft Toe, Leather Upper, Mesh Lining, Waterproof, EW Width, 6 in Height When you’re in and out of the warehouse, these work-to-office boots deliver comfort with the customer facing look you need. Built lightweight, these moc toe safety toe boots keep feet comfortable and stress-free with a breathable lining and fatigue fighting reinforcement. Features:  Premium leather upper for a look and feel that stands out Breathable waterproof membrane with a moisture wicking mesh lining for all-weather protection and comfort Goodyear® welt construction allows these boots to be resoled so they can last you for the long haul Genuine full grain leather upper gives a versatile look Time tested Goodyear® welt construction Removable full cushion footbed Lightweight nylon shank fights fatigue  Other Attributes:   \nSKU: \xa0 W0828811EW \nWidth: \xa0 EW \nToe Type: \xa0 Moc, Soft \nSize: \xa0 SZ 11 \nHeight: \xa0 6in \nSeries: \xa0 W08288 Series \nWaterproof/Non-Waterproof: \xa0 Waterproof \nUpper Material: \xa0 Leather \nColor: \xa0 Tan \nLining Material: \xa0 Mesh "), Document(id='e04e2d0e-312d-4c7a-b88e-0f63bb0e12b8', metadata={'source': 'D:\\lang_shop\\products.json', 'seq_num': 6666, 'id': 7883896455320, 'title': "Wolverine® W220040 Series W220040-6M Women's Floorhand Romeo Work Boots, SZ 6, M W, Dark Brown, Soft Toe, Waterproof", 'tags': '', 'image_list': ['https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W220040_10M_3fd572af-7c23-4206-8d98-d2ebde67149b.jpg?v=1709135415', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W220040_10M_2_b82c467c-b667-4c2c-88da-4d34f666fa56.jpg?v=1709135415', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W220040_10M_1_38c8414b-816f-416d-9dd5-c5f623fd3039.jpg?v=1709135415', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W220040_10M_3_c5c091d8-b170-4a68-89f7-00914c634243.jpg?v=1709135415', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W220040_10M_4_78b3bb6d-dca0-413a-be3a-21b79ecd88fa.jpg?v=1709135415'], 'handle': 'wolv-floorhand-wp-wms'}, page_content="Title: Wolverine® W220040 Series W220040-6M Women's Floorhand Romeo Work Boots, SZ 6, M W, Dark Brown, Soft Toe, WaterproofWolverine® Women's Floorhand Romeo Work Boots, W220040 Series, SZ 6, Dark Brown, Soft Toe, Leather Upper, Rubber Midsole, Rubber Outsole, Mesh Lining, Waterproof, M Width The floorhand waterproof work boot stands up to the test with moisture wicking mesh lining to provide additional comfort. Features:  Premium waterproof full grain leather upper Breathable waterproof membrane with moisture wicking mesh lining Removable full cushion footbed molds to the foot Rubber outsole grips the ground Lightweight cement construction Nylon shank gives extra strength  Other Attributes:   \nSKU: \xa0 W2200406M \nMidsole Material: \xa0 Rubber \nWidth: \xa0 M \nToe Type: \xa0 Soft \nSize: \xa0 SZ 6 \nSeries: \xa0 W220040 Series \nLining Material: \xa0 Mesh \nOutsole Material: \xa0 Rubber \nWaterproof/Non-Waterproof: \xa0 Waterproof \nUpper Material: \xa0 Leather \nColor: \xa0 Dark Brown "), Document(id='7430077d-bc32-4a69-a42b-013047557593', metadata={'source': 'D:\\lang_shop\\products.json', 'seq_num': 6660, 'id': 7883889803416, 'title': "Wolverine® W08288 Series W08288-95M Men's Work Boots, SZ 9.5, M W, Tan, Moc, Soft Toe, Leather Upper, Waterproof", 'tags': '', 'image_list': ['https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_447deeed-30d7-4ed3-a020-bc7236f79b89.jpg?v=1709209821', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_4_98dd0ebe-236f-4c08-8bee-7b1e7ec32ea3.jpg?v=1709209821', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_3.jpg?v=1709209821', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_1.jpg?v=1709209821', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_2_c37a9503-5910-4fa3-a077-5ed3e6e7ddac.jpg?v=1709209821'], 'handle': 'wolv-work-wedge-moc-toe'}, page_content="Title: Wolverine® W08288 Series W08288-95M Men's Work Boots, SZ 9.5, M W, Tan, Moc, Soft Toe, Leather Upper, WaterproofWolverine® Men's Work Boots, W08288 Series, SZ 9.5, Tan, Moc, Soft Toe, Leather Upper, Mesh Lining, Waterproof, M Width, 6 in Height When you’re in and out of the warehouse, these work-to-office boots deliver comfort with the customer facing look you need. Built lightweight, these moc toe safety toe boots keep feet comfortable and stress-free with a breathable lining and fatigue fighting reinforcement. Features:  Premium leather upper for a look and feel that stands out Breathable waterproof membrane with a moisture wicking mesh lining for all-weather protection and comfort Goodyear® welt construction allows these boots to be resoled so they can last you for the long haul Genuine full grain leather upper gives a versatile look Time tested Goodyear® welt construction Removable full cushion footbed Lightweight nylon shank fights fatigue  Other Attributes:   \nSKU: \xa0 W0828895M \nWidth: \xa0 M \nToe Type: \xa0 Moc, Soft \nSize: \xa0 SZ 9.5 \nHeight: \xa0 6in \nSeries: \xa0 W08288 Series \nWaterproof/Non-Waterproof: \xa0 Waterproof \nUpper Material: \xa0 Leather \nColor: \xa0 Tan \nLining Material: \xa0 Mesh "), Document(id='2f00813b-48ba-45b8-a8cc-8297f7c35079', metadata={'source': 'D:\\lang_shop\\products.json', 'seq_num': 6665, 'id': 7883893571736, 'title': "Wolverine® W10841 Series W10841-95M Men's Loader Wedge Work Boots, SZ 9.5, M W, Cafe, Safety Toe, Leather Upper", 'tags': '', 'image_list': ['https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W10841_105EW_f1a6c650-1801-4c13-947a-c541701cca69.jpg?v=1709208839', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W10841_105EW_2_545c18aa-15a2-40d8-aa1e-d284744d008b.jpg?v=1709208839', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W10841_105EW_1.jpg?v=1709208840', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W10841_105EW_4_2839414d-9706-43d8-915b-f410ef2973f3.jpg?v=1709208840', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W10841_105EW_3_81e78888-5a7d-4d20-8c96-41bfaf7206ac.jpg?v=1709208840'], 'handle': 'wolv-loader-wp-6'}, page_content="Title: Wolverine® W10841 Series W10841-95M Men's Loader Wedge Work Boots, SZ 9.5, M W, Cafe, Safety Toe, Leather UpperWolverine® Men's Loader Wedge Work Boots, W10841 Series, SZ 9.5, Cafe, Safety Toe, Leather Upper, Polyurethane Outsole, Waterproof, M Width, 6 in Height Style meets practicality in the wolverine® Loader work wedge. This boot provides comfort all-day long and can go from the construction site to the office without any change of shoe. Goodyear® welt construction allows these boots to be resoled so they can last you for the long haul. Features:  Premium leather upper that looks and feels premium Breathable waterproof membrane lining with a padded collar for instant comfort Removable full cushioned footbed Polyurethane wedge outsole that grips the ground Timeless Goodyear® welt construction  Other Attributes:   \nSKU: \xa0 W10841-95M \nWidth: \xa0 M \nOutsole Material: \xa0 Polyurethane \nToe Type: \xa0 Safety \nSize: \xa0 SZ 9.5 \nHeight: \xa0 6in \nSeries: \xa0 W10841 Series \nWaterproof/Non-Waterproof: \xa0 Waterproof \nUpper Material: \xa0 Leather \nColor: \xa0 Cafe "), Document(id='76a61e85-00d9-41d7-b4b6-74634fe6cff5', metadata={'source': 'D:\\lang_shop\\products.json', 'seq_num': 1245, 'id': 7883806081176, 'title': "KEEN 1018023 Series 1018023-9-D Men's Coburg Heavy-Duty Work Boots, SZ 9, D W, Cascade Brown/Brindle, Steel Toe", 'tags': '', 'image_list': ['https://cdn.shopify.com/s/files/1/0600/7344/3480/products/KEEN_1018023_10_5_D.jpg?v=1709118325', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/KEEN_1018023_10_5_D_3.jpg?v=1709118325', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/KEEN_1018023_10_5_D_1.jpg?v=1709118325', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/KEEN_1018023_10_5_D_2.jpg?v=1709118325'], 'handle': 'keen-corburg'}, page_content="Title: KEEN 1018023 Series 1018023-9-D Men's Coburg Heavy-Duty Work Boots, SZ 9, D W, Cascade Brown/Brindle, Steel ToeKEEN Men's Coburg Heavy-Duty Work Boots, 1018023 Series, SZ 9, Cascade Brown/Brindle, Steel Toe, Leather Upper, Polyurethane Midsole, Rubber Outsole, Heel Style: Contoured, 5/8 in Heel Height, Lace Closure, Waterproof, Resists: Heat, Oil and Slip, D Width, 6 in Height Made for when the going gets tough, these 6 in steel toe work boots feature a KEEN.DRY waterproof, breathable membrane, moisture wicking interior and durable leather construction to keep you in reliable comfort and support from sunup to sundown. Assembled in the pacific northwest using carefully sourced materials from around the world. Features:  American built using the finest materials from around the world Left and right asymmetrical steel toes offering maximum comfort and unobtrusive fit KEEN.DRY waterproof, breathable membrane Contoured heel guard protects against bumps and scrapes, plus normal wear and tear TPU shank for midfoot support 90 deg heel provides stability and helps catch or lock the foot in place Electrical hazard (EH) or electric shock resistant (ESR) footwear provides a secondary source of protection in case accidentally coming into contact with live electrical circuits Environmentally preferred premium leather from LWG certified tannery PFC-free, durable water repellent  Standard Approvals: ASTM F3445-21|F2413-18 M I/75 C/75 EH|ASTM F1677-96|ASTM D471-06 903 Application: For road construction, construction, mechanic, natural resources and fabricator Other Attributes:   \nSKU: \xa0 10180239D \nSize: \xa0 SZ 9 \nHeel Style: \xa0 Contoured \nUpper Material: \xa0 Leather \nHeight: \xa0 6in \nSeries: \xa0 1018023 Series \nColor: \xa0 Cascade Brown/Brindle \nWidth: \xa0 D \nResists: \xa0 Heat, Oil and Slip \nHeel Height: \xa0 5/8in \nOutsole Material: \xa0 Rubber \nWaterproof/Non-Waterproof: \xa0 Waterproof \nToe Type: \xa0 Steel \nMidsole Material: \xa0 Polyurethane \nClosure Type: \xa0 Lace "), Document(id='8cfea00d-8b77-4b08-a25f-e6d69bafbc08', metadata={'source': 'D:\\lang_shop\\products.json', 'seq_num': 6658, 'id': 7883889213592, 'title': "Wolverine® W08285 Series W08285-9EW Men's Wellington Work Boots, SZ 9, EW W, Brown, Soft Toe, Leather Upper", 'tags': '', 'image_list': ['https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08285_105EW_d65d0568-6f41-406c-a514-6e296e00b48a.jpg?v=1709133972', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08285_105EW_1_cc29c44e-9f28-41b6-9c03-c2d750f62d84.jpg?v=1709133972'], 'handle': 'wolv-work-wedge-brn'}, page_content="Title: Wolverine® W08285 Series W08285-9EW Men's Wellington Work Boots, SZ 9, EW W, Brown, Soft Toe, Leather UpperWolverine® Men's Wellington Work Boots, W08285 Series, SZ 9, Brown, Soft Toe, Leather Upper, Rubber Midsole, EW Width, 10 in Height This rugged slip-on wellington is simply built for the ins and outs of tough days at work. This all leather boot keeps your feet going with flexible, enduring Goodyear® construction, arch support and a removable cushioned footbed. Features:  Rugged, genuine full grain leather upper Durable, flexible Goodyear® welt construction that allows for resoling and many years of wear Unlined to keep boot light and breathable Fatigue fighting comfort from removable full cushion footbed and lightweight arch support  Other Attributes:   \nSKU: \xa0 W082859EW \nMidsole Material: \xa0 Rubber \nWidth: \xa0 EW \nToe Type: \xa0 Soft \nSize: \xa0 SZ 9 \nHeight: \xa0 10in \nSeries: \xa0 W08285 Series \nUpper Material: \xa0 Leather \nColor: \xa0 Brown "), Document(id='9703c395-4140-4dd7-90c6-79c6032737e9', metadata={'source': 'D:\\lang_shop\\products.json', 'seq_num': 6661, 'id': 7883890262168, 'title': "Wolverine® W08289 Series W08289-95EW Men's Work Boots, SZ 9.5, EW W, Tan, Moc, Steel Toe, Leather Upper", 'tags': '', 'image_list': ['https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_e082dd42-38a5-4adc-9c08-b9dfaa13bb20.jpg?v=1709208817', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_1_94f562d7-2cb7-4797-92bc-d7d2b9487c59.jpg?v=1709208817', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_4.jpg?v=1709208817', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_2.jpg?v=1709208817', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_3_a03107cb-d695-4a04-8101-d74256d9a3cf.jpg?v=1709208817'], 'handle': 'wolv-work-wedge-steel-toe'}, page_content="Title: Wolverine® W08289 Series W08289-95EW Men's Work Boots, SZ 9.5, EW W, Tan, Moc, Steel Toe, Leather UpperWolverine® Men's Work Boots, W08289 Series, SZ 9.5, Tan, Moc, Steel Toe, Leather Upper, Fabric Lining, EW Width, 6 in Height When you’re in and out of the warehouse, these work-to-office boots deliver comfort with the customer facing look you need. Built lightweight, these moc toe safety toe boots keep feet comfortable and stress-free with a breathable lining and fatigue fighting reinforcement. Features:  Genuine full grain leather upper gives a versatile look Time tested Goodyear® welt construction Breathable fabric linings for comfort Removable full cushion footbed Lightweight nylon shank fights fatigue  Standard Approvals: ASTM F2413-18 M/I/C EH Other Attributes:   \nSKU: \xa0 W0828995EW \nWidth: \xa0 EW \nToe Type: \xa0 Moc, Steel \nSize: \xa0 SZ 9.5 \nHeight: \xa0 6in \nUpper Material: \xa0 Leather \nColor: \xa0 Tan \nSeries: \xa0 W08289 Series \nLining Material: \xa0 Fabric "), Document(id='64688a72-9dba-4bb9-a8f7-5a78d28f633c', metadata={'source': 'D:\\lang_shop\\products.json', 'seq_num': 1301, 'id': 7883811455128, 'title': "KEEN 1026704 Series 1026704-9-EE Men's Vista Energy+ Shift Medium-Duty Boots, SZ 9, EE W, Coffee Bean/Black", 'tags': '', 'image_list': ['https://cdn.shopify.com/s/files/1/0600/7344/3480/products/KEEN_1026704_105_D_e28a619d-5be5-4bed-95f0-6e15b8745b28.jpg?v=1709119221', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/KEEN_1026704_105_D_3_7c598a97-d757-4907-9a2b-42f3ea89660a.jpg?v=1709119221', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/KEEN_1026704_105_D_2_92666abb-b9e3-44a7-a180-963419a5fa22.jpg?v=1709119221', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/KEEN_1026704_105_D_1_b057aea8-c085-4552-b7a2-825132cb82cc.jpg?v=1709119221'], 'handle': 'keen-vista-shift'}, page_content="Title: KEEN 1026704 Series 1026704-9-EE Men's Vista Energy+ Shift Medium-Duty Boots, SZ 9, EE W, Coffee Bean/BlackKEEN Men's Vista Energy+ Shift Medium-Duty Boots, 1026704 Series, SZ 9, Coffee Bean/Black, Carbon Fiber Toe, Leather Upper, Rubber Outsole, Resists: Oil and Slip, EE Width Designed with a new abrasion-resistant leather upper and incorporating a proven energy returning KEEN.ReGEN cushioning midsole, this men's work sneaker keeps you comfortable and active while also protecting what you're working on. An ESD rated outsole, easy-on/easy-off lace less design and lightweight carbon fiber toes max out the workflow enhancing feature set. Features:  Left and right asymmetrical, non-metallic carbon fiber toes offer unobtrusive fit and are 15% lighter than steel Nylon shank for midfoot support Electro static dissipative (ESD) or super-static dissipative (SD+) footwear is constructed to reduce excess static electricity Environmentally preferred premium leather from LWG certified tannery PFC-free, durable water repellent  Application: For warehouse, assembly line, light manufacturing and aerospace Other Attributes:   \nSKU: \xa0 1026704-9EE \nSeries: \xa0 1026704 Series \nUpper Material: \xa0 Leather \nWidth: \xa0 EE \nResists: \xa0 Oil and Slip \nToe Type: \xa0 Carbon Fiber \nOutsole Material: \xa0 Rubber \nColor: \xa0 Coffee Bean/Black \nSize: \xa0 SZ 9 "), Document(id='9482af36-799b-4e75-b11a-35b128296de0', metadata={'source': 'D:\\lang_shop\\products.json', 'seq_num': 3275, 'id': 7661269287064, 'title': 'Muck Boot Company® CHH-000A-BL-09 Chore Classic Work Boots, SZ 9, M W, Black, Rubber Outsole, Pull-Tab Closure', 'tags': '', 'image_list': ['https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Muck_Boot_Company_CHH_000A_BL_10.jpg?v=1709128484', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Muck_Boot_Company_CHH_000A_BL_10_1.jpg?v=1709128484', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Muck_Boot_Company_CHH_000A_BL_10_2.jpg?v=1709128484', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Muck_Boot_Company_CHH_000A_BL_10_4.jpg?v=1709128484', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Muck_Boot_Company_CHH_000A_BL_10_3_20c2ff4e-bf97-4322-b346-1210d8786a2e.jpg?v=1709128484'], 'handle': 'boots-muck-chore-hi-9m'}, page_content='Title: Muck Boot Company® CHH-000A-BL-09 Chore Classic Work Boots, SZ 9, M W, Black, Rubber Outsole, Pull-Tab ClosureMuck Boot Company® Chore Classic Work Boots, SZ 9, Black, Rubber Outsole, Heel Style: Quadruple, 1.1 in Heel Height, Neoprene Lining, Pull-Tab Closure, Waterproof, M Width, 15.9 in Height, Additional Information: 16-1/2 in Calf Circumference, 3.6 in W Footbed You can guarantee that our best selling chore collection provides the comfort and protection that a work boot needs, to handle the toughest of jobs. The chore classic is a reliable work boot with its rugged and dependable design, perfect for farmers or simply for trudging across muddy fields. These work boots feature a rubber overlay and quick cleaning sole, allowing you more time to get on with the important stuff. With a comfortable neoprene top-line, this work boot stretches for the perfect fit around wide calves. The upper is reinforced in both the toe and heel area, plus additional arch support giving you the protection you need. The 5 mm neoprene makes these boots lightweight and flexible, with breathable mesh lining to keep you cool on warmer days. Features:  5 mm CR flex-foam neoprene liner is 100% waterproof with exceptional comfort, flexibility, shock absorption and heat retention properties, adjusts to the contours of your foot to resist blisters and chafing Breathable mesh lining wicks away humidity and perspiration, allowing air to travel throughout the boot Easy to clean rubber overlays Triple rubber toe reinforcement Quadruple rubber heel reinforcement Steel shank for structural support Stretch fit topline binding snugs calf to keep warmth in and cold out Quick cleaning rubber outsole offers durability and traction on slick surfaces Reflective pull-tab for easy on and off 

In [141]:
import requests
from dotenv import load_dotenv 
import os

load_dotenv()

header = {
    'Content-Type' : "application/json",
    'Authorization' : "Bearer " +  os.getenv("SHOPIFY_API_KEY")
}
response = requests.get('http://127.0.0.1:8000/product_search', params={'query': 'work boots', 'k': 10},headers=header)
print(response.json()[0]['metadata'])

{'source': 'D:\\lang_shop\\products.json', 'seq_num': 6659, 'id': 7883890196632, 'title': "Wolverine® W08288 Series W08288-11EW Men's Work Boots, SZ 11, EW W, Tan, Moc, Soft Toe, Leather Upper, Waterproof", 'tags': '', 'image_list': ['https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_7c38f3e3-966f-4d88-8b1b-eb5d02cc9658.jpg?v=1709133517', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_2_899509a8-1cd8-48bc-b7b9-c7f82650901b.jpg?v=1709133517', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_4_6b20edf6-9042-43c4-8d98-7048ac581963.jpg?v=1709133517', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_1_f0b00c7c-1208-4a9c-b074-b354aeebac7b.jpg?v=1709133517', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_3_f4a10372-235f-4112-93f6-be2d43c4836b.jpg?v=1709133517'], 'handle': 'work-wedge-brn-moc-toe-11-ew'}

In [107]:
import os
import base64
token_bytes = os.urandom(24)
safe_token = base64.urlsafe_b64encode(token_bytes).decode('utf-8')
print(safe_token)
print("token length : ", len(safe_token))

VBo1ygA7n-sKyDL1JvorI_uYDsKcLgDJ
token length :  32

In [106]:
"https://jacksonshardware.myshopify.com/products/"+response.json()[3]["metadata"]["handle"]

'https://jacksonshardware.myshopify.com/products/boots-muck-chore-hi-9m'

In [139]:
print(response.json()[0]["metadata"]["image_list"])

['https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_7c38f3e3-966f-4d88-8b1b-eb5d02cc9658.jpg?v=1709133517', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_2_899509a8-1cd8-48bc-b7b9-c7f82650901b.jpg?v=1709133517', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_4_6b20edf6-9042-43c4-8d98-7048ac581963.jpg?v=1709133517', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_1_f0b00c7c-1208-4a9c-b074-b354aeebac7b.jpg?v=1709133517', 'https://cdn.shopify.com/s/files/1/0600/7344/3480/products/Wolverine_W08288_105EW_3_f4a10372-235f-4112-93f6-be2d43c4836b.jpg?v=1709133517']